### ISSUE TITLE
MapServer.cpp  questions

### ISSUE THREAD

**Issue by Bryan-bai** [UbiCALab/cam_exploration#1]
Dear,
I have some questions about the source codes.

1. MapServer.cpp  line 422
int MapServer::right(int cell)
{
  // only go left if no index error and if current cell is not already on the left boundary
  if ((cell % map.info.width != 0))  
    return cell + 1;

  return -1;
}
** I think that cell should be cell+1.     **if ((cell % map.info.width != 0))  **
MapServer::upright(int cell) ...  also should be cell+1 
Am I right? **

2.MapServer.cpp  line 360
**I think that the order should be left upleft up upright right .....   otherwise, in void MapServer::findFrontiers() ( from line198 to line 235 in MapServer.cpp)   the ordered_cells maybe lost some frontiers. for instance: the labels like this 
0 1 0 0 0 0 1 0 0 0 0 0 
0 1 1 1 1 1 1 0 0 0 0 0
0 0 0 0 0 0 1 0 0 0 0 0 
0 0 0 0 0 0 1 0 0 0 0 0
0 0 0 0 0 0 1 0 0 0 0 0    
the 1 in the last 3 rows will not be pushed into the ordered_cells. Thus the middle cell will not correct. Am I right?**  
void MapServer::getAdjacentPoints(int cell, int cells[])
{
  cells[0] = left(cell);
  cells[1] = up(cell);
  cells[2] = right(cell);
  cells[3] = down(cell);
  cells[4] = upleft(cell);
  cells[5] = upright(cell);
  cells[6] = downright(cell);
  cells[7] = downleft(cell);
}

3.replan.cpp line 98
bool TooMuchTimeNearGoal::isOriented()
{
    geometry_msgs::Quaternion robot_orintation = RobotMotion::pose().orientation;
    geometry_msgs::Quaternion current_goal = RobotMotion::current_goal().orientation;

    tf::Quaternion quat_robot, quat_goal;
    tf::quaternionMsgToTF(robot_orintation, quat_robot);
    tf::quaternionMsgToTF(current_goal, quat_goal);

    tfScalar diff = M_PI - quat_robot.angle(quat_goal);
    //ROS_INFO("Diff: %f. Threshold: %f. Is oriented? %d", diff, orientation_th, diff < orientation_th);
    return diff < orientation_th;
}
** tfScalar diff = M_PI - quat_robot.angle(quat_goal);**
** I think diff should be diff=quat_robot.angle(quat_goal);     return the different angel between current orientation and the goal orientation **

Because I am not sure about these, Can you help me ?

**Comment by vikcp** [comment]
Hi, 
I will have a look as soon as I have some free time, this code was created by a colleague and I have not look at it.

**Comment by Bryan-bai** [comment]
Hi，
Thanks！



Best Wishes！


Jinqiang Bai
Email:baijinqiangupc@163.com
 
From: Víctor Casamayor Pujol
Date: 2017-04-19 16:57
To: UbiCALab/cam_exploration
CC: Bryan-bai; Author
Subject: Re: [UbiCALab/cam_exploration] MapServer.cpp questions (#1)
Hi,
I will have a look as soon as I have some free time, this code was created by a colleague and I have not look at it.

**Comment by vikcp** [comment]
Hi, 

I'm sorry for the delay, but I have been busy with other stuff. However, these days I have been able to look at the code and I will try to answer your questions.

Regarding the first question, the code is fine. You are looking no to be at the edge by doing the modulus of your position with respect to the maps limits. Therefore, if you are not at the edge you will be able to move at least one cell towards the considered direction. If you use _cell+1_ you are checking the next cell which could be at the edge, and you could move to it, but the code will tell you that you can't.

2nd question.
Here is a bit more complicated, actually you are right saying that with the example that your propose some _1s_ will be out of the frontier and therefore the center will not be well computed. 
Nevertheless, the solution that you are considering does not solve the problem, if you consider a case which is symmetric with respect the one you proposed and suppose you start from the "italic" 1:
**0 1 0 0 1 0 0**
**0 1 1 1 _1_ 0 0**
**0 1 0 0 0 0 0**
**0 1 0 0 0 0 0**
**0 1 0 0 0 0 0**
You will also leave the bottom ones not included.
Here the problem is how to order things, because there is no a correct rule to do so. You could try to remember all the possible accessible cells by removing the break, and moving then afterwards, but which will you visit first? The one on top or the one on bottom? There is no rule for that, therefore I can't thing on a better solution now, however, I will keep looking and thinking on it.

3rd Question. Here the answer is easy, and just a matter of conventions, without the M_PI your result will be from _0_ to _2pi_ however, with the M_PI, your output is from _pi_ to _-pi_.
The second options is usually better in order to compare and work with angles.

I hope it helps.

Best regards.

Víctor.

**Comment by Bryan-bai** [comment]
Hi,
Thanks for your detailed explanation. This is very helpful for me.

Best regards.
Jinqiang Bai
